colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true

mainSections = ["posts"]

disableImageOptimization = false
disableTextInHeader = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showHero = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  seriesOpened = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  showZenMode = false
  sharingLinks = ["twitter", "reddit", "linkedin", "email"]

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = true
  showTableOfContents = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
